version: "3.9"

services:
  nextgba:
    container_name: nextgba
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./data/games:/app/public/games
